music.setTempo(300)
music.playTone(220, music.beat(BeatFraction.Whole))
basic.pause(50)
music.playTone(220, music.beat(BeatFraction.Half))
basic.pause(50)
music.playTone(220, music.beat(BeatFraction.Half))
basic.pause(50)
music.playTone(220, music.beat(BeatFraction.Whole))
basic.pause(50)
music.playTone(262, music.beat(BeatFraction.Whole))
basic.pause(50)
music.playTone(330, music.beat(BeatFraction.Half))
basic.pause(50)
music.playTone(330, music.beat(BeatFraction.Half))
basic.pause(50)
music.playTone(330, music.beat(BeatFraction.Whole))
basic.pause(50)
music.playTone(330, music.beat(BeatFraction.Whole))
basic.pause(50)
music.playTone(330, music.beat(BeatFraction.Whole))
basic.pause(50)
music.playTone(349, music.beat(BeatFraction.Whole))
basic.pause(50)
music.playTone(294, music.beat(BeatFraction.Half))
basic.pause(50)
music.playTone(294, music.beat(BeatFraction.Half))
basic.pause(50)
music.playTone(294, music.beat(BeatFraction.Whole))
basic.pause(50)
music.playTone(349, music.beat(BeatFraction.Whole))
basic.pause(50)
music.playTone(440, music.beat(BeatFraction.Half))
basic.pause(50)
music.playTone(440, music.beat(BeatFraction.Half))
basic.pause(50)
music.playTone(330, music.beat(BeatFraction.Whole))
basic.pause(50)
music.playTone(330, music.beat(BeatFraction.Double))
basic.pause(100)
music.playTone(220, music.beat(BeatFraction.Whole))
basic.pause(50)
music.playTone(220, music.beat(BeatFraction.Half))
basic.pause(50)
music.playTone(220, music.beat(BeatFraction.Half))
basic.pause(50)
music.playTone(220, music.beat(BeatFraction.Whole))
basic.pause(50)
music.playTone(262, music.beat(BeatFraction.Whole))
basic.pause(50)
music.playTone(330, music.beat(BeatFraction.Half))
basic.pause(50)
music.playTone(330, music.beat(BeatFraction.Half))
basic.pause(50)
music.playTone(330, music.beat(BeatFraction.Whole))
basic.pause(50)
music.playTone(330, music.beat(BeatFraction.Whole))
basic.pause(50)
music.playTone(330, music.beat(BeatFraction.Whole))
basic.pause(50)
music.playTone(330, music.beat(BeatFraction.Whole))
basic.pause(50)
music.playTone(294, music.beat(BeatFraction.Whole))
basic.pause(50)
music.playTone(262, music.beat(BeatFraction.Whole))
basic.pause(70)
music.playTone(247, music.beat(BeatFraction.Whole))
basic.pause(70)
music.playTone(220, music.beat(BeatFraction.Breve))
basic.pause(100)
music.playTone(440, music.beat(BeatFraction.Double))
basic.pause(70)
music.playTone(440, music.beat(BeatFraction.Double))
basic.pause(70)
music.playTone(349, music.beat(BeatFraction.Half))
basic.pause(50)
music.playTone(392, music.beat(BeatFraction.Half))
basic.pause(50)
music.playTone(392, music.beat(BeatFraction.Half))
basic.pause(50)
music.playTone(330, music.beat(BeatFraction.Whole))
basic.pause(50)
music.playTone(330, music.beat(BeatFraction.Whole))
basic.pause(50)
music.playTone(330, music.beat(BeatFraction.Whole))
basic.pause(50)
music.playTone(349, music.beat(BeatFraction.Whole))
basic.pause(50)
music.playTone(294, music.beat(BeatFraction.Half))
basic.pause(50)
music.playTone(294, music.beat(BeatFraction.Half))
basic.pause(50)
music.playTone(294, music.beat(BeatFraction.Whole))
basic.pause(50)
music.playTone(349, music.beat(BeatFraction.Whole))
basic.pause(50)
music.playTone(440, music.beat(BeatFraction.Half))
basic.pause(50)
music.playTone(440, music.beat(BeatFraction.Half))
basic.pause(50)
music.playTone(330, music.beat(BeatFraction.Whole))
basic.pause(50)
music.playTone(330, music.beat(BeatFraction.Double))
basic.pause(100)
music.playTone(440, music.beat(BeatFraction.Double))
basic.pause(50)
music.playTone(440, music.beat(BeatFraction.Double))
basic.pause(50)
music.playTone(349, music.beat(BeatFraction.Half))
basic.pause(50)
music.playTone(392, music.beat(BeatFraction.Half))
basic.pause(50)
music.playTone(392, music.beat(BeatFraction.Half))
basic.pause(50)
music.playTone(330, music.beat(BeatFraction.Whole))
basic.pause(50)
music.playTone(330, music.beat(BeatFraction.Whole))
basic.pause(50)
music.playTone(330, music.beat(BeatFraction.Whole))
basic.pause(50)
music.playTone(330, music.beat(BeatFraction.Whole))
basic.pause(50)
music.playTone(294, music.beat(BeatFraction.Whole))
basic.pause(50)
music.playTone(262, music.beat(BeatFraction.Whole))
basic.pause(70)
music.playTone(247, music.beat(BeatFraction.Whole))
basic.pause(70)
music.playTone(220, music.beat(BeatFraction.Double))
